cpu:
  svd: stm32f407.svd
  vector_table: 0x08020000
regions:
  - name: ROM
    start: 0x08020000
    load: saturn-v4.4.3-pj-v5.bin
    size: 0x80000
  - name: RAM-CCM
    start: 0x10000000
    size: 0x18000
  - name: RAM
    start: 0x20000000
    size: 0x20000
